-- 既存のテーブルとタイプを削除
DROP TABLE IF EXISTS contacts;
DROP TYPE IF EXISTS inquiry_type;
DROP TYPE IF EXISTS contact_status;

-- 列挙型の作成
CREATE TYPE inquiry_type AS ENUM (
    'ses',
    'backup',
    'saas',
    'other',
    'recruitment'
);

CREATE TYPE contact_status AS ENUM (
    'pending',
    'in_progress',
    'completed',
    'rejected'
);

-- テーブルの作成
CREATE TABLE contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    company TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    inquiry_type inquiry_type NOT NULL,
    message TEXT NOT NULL,
    status contact_status DEFAULT 'pending' NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 更新時のタイムスタンプを自動更新する関数とトリガー
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_contacts_updated_at
    BEFORE UPDATE ON contacts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- インデックスの作成
CREATE INDEX contacts_created_at_idx ON contacts(created_at);
CREATE INDEX contacts_status_idx ON contacts(status);
CREATE INDEX contacts_inquiry_type_idx ON contacts(inquiry_type);

-- RLSポリシーの設定
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous insert" ON contacts
    FOR INSERT
    TO anon
    WITH CHECK (true);

CREATE POLICY "Allow authenticated full access" ON contacts
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE TABLE contacts_backup AS SELECT * FROM contacts;